#4, #5. Сервис для получения информации о фильмах.
AndreyNikitsich/team_async_api_sprint_1 pull request #19
Opened 2024-01-22 08:57 UTC by vladmeh

Создал сервис фильмов.
Немного подправил config.

2024-01-22 10:09 UTC, AndreyNikitsich requested changes

2024-01-22 10:09 UTC, AndreyNikitsich commented on src/models/film.py
> +        json_loads = orjson.loads
может встроенной сереализацией Pydantic будем пользоваться ? Вторая версия, которой мы пользуемся, тоже на Rust реализована и работает быстро

2024-01-22 10:09 UTC, AndreyNikitsich commented on src/services/film.py
> +                index="movies",
в конфиг бы вынести

2024-01-22 10:09 UTC, AndreyNikitsich commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
поддержим возможность писать в sort список ключей ?

2024-01-22 10:09 UTC, AndreyNikitsich commented on src/services/film.py
> +            genre: str | None
жанров может быть много, можем как и для sort поддержать list ?

2024-01-22 10:09 UTC, AndreyNikitsich commented on src/core/config.py
> +    CACHE_EXPIRE_IN_SECONDS: int = Field(default=(60 * 5))
default можно указывать просто через присвоение, без использования Field

2024-01-22 11:06 UTC, AndreyNikitsich requested changes

2024-01-22 11:06 UTC, AndreyNikitsich commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
а почему в списке фильмов может быть None вместо фильма ?

2024-01-22 11:06 UTC, AndreyNikitsich commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
еще хотелось бы получать total count фильмов по запросу, чтобы на фронте можно было отображать кол-во страниц, раз пагинацию делаем

2024-01-22 11:14 UTC, vladmeh commented on src/models/film.py
> +        json_loads = orjson.loads
Согласен

2024-01-22 11:18 UTC, vladmeh commented on src/core/config.py
> +    CACHE_EXPIRE_IN_SECONDS: int = Field(default=(60 * 5))
Согласен

2024-01-22 11:23 UTC, vladmeh commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
> а почему в списке фильмов может быть None вместо фильма ?

Потому, что 
1. База пустая
2. по запросу ничего нет

2024-01-22 11:26 UTC, AndreyNikitsich requested changes

2024-01-22 11:26 UTC, AndreyNikitsich commented on src/models/film.py
> +    actors: list[FilmPerson] | None = Field([])
В предыдущем срипнте мы должны были загрузить в эластик данные по актерам, режиссерам, директорам и жанрам в виде списка. None не должен появляться в этих полях

2024-01-22 11:29 UTC, vladmeh commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
> еще хотелось бы получать total count фильмов по запросу, чтобы на фронте можно было отображать кол-во страниц, раз пагинацию делаем

Зачем? Это есть в ТЗ?
Если уж совсем правильно, то нужно помимо total_count_films, еще и total_page, current_page, count_films_on_page.

2024-01-22 11:30 UTC, AndreyNikitsich commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
Ты же добавляешь фильмы в список на строке 119. Как там может None появится вместо фильма ?

2024-01-22 11:30 UTC, vladmeh commented on src/services/film.py
> +                index="movies",
Согласен

2024-01-22 11:31 UTC, vladmeh commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
???

2024-01-22 11:36 UTC, AndreyNikitsich commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
> > еще хотелось бы получать total count фильмов по запросу, чтобы на фронте можно было отображать кол-во страниц, раз пагинацию делаем
> 
> Зачем? Это есть в ТЗ? Если уж совсем правильно, то нужно помимо total_count_films, еще и total_page, current_page, count_films_on_page.

В тз этого нет, согласен

2024-01-22 11:44 UTC, AndreyNikitsich commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
> поддержим возможность писать в sort список ключей ?

сейчас сортировка доступна только по одному полю - рейтинг. Мы можем использовать вместо строки список и тогда, при расширении функционала, нам не придется править сервис для поддержания сортировки по нескольким ключам одновременно (например, рейтинг и дата выхода в прокат)

2024-01-22 11:44 UTC, vladmeh commented on src/services/film.py
> +            genre: str | None
А где мы будем фильтровать фильмы по нескольким жанрам?

2024-01-22 11:46 UTC, vladmeh commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
Как будет запрос в ручке?

2024-01-22 11:48 UTC, AndreyNikitsich commented on src/services/film.py
> +            genre: str | None
> А где мы будем фильтровать фильмы по нескольким жанрам?

На демо я задавал вопрос овнеру по поводу похожести фильмов. В тз предложено реализовать это как вывод фильмов того же жанра, что и исходный. Фильм может иметь больше одного жанра. От овнера получил ответ, что мы должны предоставить в ответ фильмы, в которых есть упоминание хотя бы одного жанра (операция OR) исходного фильма

2024-01-22 11:51 UTC, vladmeh commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
> Ты же добавляешь фильмы в список на строке 119. Как там может None появится вместо фильма ?

А в строке 117 я возвращаю пустой список

2024-01-22 11:52 UTC, AndreyNikitsich commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
> Как будет запрос в ручке?

например так /api/v1/films?genre=action&genre=crime

2024-01-22 12:02 UTC, AndreyNikitsich commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
> > Ты же добавляешь фильмы в список на строке 119. Как там может None появится вместо фильма ?
> 
> А в строке 117 я возвращаю пустой список

именно, он пустой, в нем нет внутри данных типа None. Ты пытаешься показать, что возвращаешь пустой список ? Не видел, чтобы это делали таким способом. Да и вообще не видел, чтобы пустой список как-то специально аннотировали. В доке написано, что Optional раскрывается как Union[YourType, None] https://docs.python.org/3/library/typing.html#typing.Optional

2024-01-22 12:06 UTC, vladmeh commented on src/services/film.py
> +            genre: str | None
> На демо я задавал вопрос овнеру по поводу похожести фильмов. В тз предложено реализовать это как вывод фильмов того же жанра, что и исходный. Фильм может иметь больше одного жанра. От овнера получил ответ, что мы должны предоставить в ответ фильмы, в которых есть упоминание хотя бы одного жанра (операция OR) исходного фильма

Полностью с тобой согласен, но 
1. Как будет выглядеть запрос в ручке (от этого и пляшем)?
2. Судя по макету (а мы типа делаем приложение по представленным макетам) будет ссылка на конкретный жанр, по которой надо показать "Жанр и популярные фильмы в нём" - цитата из ТЗ. Я не думаю что пользователь сам будет вводить в адресной строке что-то типа `/api/v1/films?genre=Фантастика,Ужасы...`

2024-01-22 12:11 UTC, AndreyNikitsich commented on src/services/film.py
> +            genre: str | None
> > На демо я задавал вопрос овнеру по поводу похожести фильмов. В тз предложено реализовать это как вывод фильмов того же жанра, что и исходный. Фильм может иметь больше одного жанра. От овнера получил ответ, что мы должны предоставить в ответ фильмы, в которых есть упоминание хотя бы одного жанра (операция OR) исходного фильма
> 
> Полностью с тобой согласен, но
> 
> 1. Как будет выглядеть запрос в ручке (от этого и пляшем)?
> 2. Судя по макету (а мы типа делаем приложение по представленным макетам) будет ссылка на конкретный жанр, по которой надо показать "Жанр и популярные фильмы в нём" - цитата из ТЗ. Я не думаю что пользователь сам будет вводить в адресной строке что-то типа `/api/v1/films?genre=Фантастика,Ужасы...`

1. Для тебя формат url не будет иметь значение. Я средствами query параметров fastapi распаршу любой из приведенных мною вариантов в коллекцию жанров, которую отправлю тебе в сервис
2. Я говорю об этом экране. Здесь выводятся похожие на этот фильм фильмы https://practicum.yandex.ru/learn/middle-python-plus-async/courses/d0d656c1-003b-4be2-92ff-c7ef3965e762/sprints/222050/topics/eca5df24-dbfe-4b9e-b8f3-a2339bc71f8a/lessons/5c3885fa-a149-485e-9ac2-0f7549949a0a/

2024-01-22 15:08 UTC, vladmeh commented on src/services/film.py
> +            genre: str | None
ок, и из еластика вытаскиваем через or, но строгое соответствие, так?

2024-01-22 15:13 UTC, vladmeh commented on src/services/film.py
> +    ) -> List[Optional[Film]]:
Ох, уж эти типы... Согласен...

2024-01-22 15:16 UTC, vladmeh commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
> например так /api/v1/films?sort=imdb_rating,date или так /api/v1/films?sort=imdb_rating&sort=date

ок, делаем списком, как и genre?

2024-01-22 15:43 UTC, vladmeh commented on src/core/config.py
> +    CACHE_EXPIRE_IN_SECONDS: int = Field(default=(60 * 5))
Ругается mypy
```
src\core\config.py:38: error: Missing named argument "PROJECT_NAME" for "SwaggerSettings"  [call-arg]
src\core\config.py:39: error: Missing named argument "REDIS_HOST" for "RedisSettings"  [call-arg]
src\core\config.py:39: error: Missing named argument "REDIS_PORT" for "RedisSettings"  [call-arg]
src\core\config.py:39: error: Missing named argument "CACHE_EXPIRE_IN_SECONDS" for "RedisSettings"  [call-arg]
src\core\config.py:40: error: Missing named argument "ES_DSN" for "ElasticSettings"  [call-arg]
src\core\config.py:40: error: Missing named argument "FILMS_INDEX" for "ElasticSettings"  [call-arg]
```

2024-01-22 15:46 UTC, AndreyNikitsich commented on src/services/film.py
> +                sort=f"{sort[1:]}:desc" if sort.startswith("-") else sort,
> > например так /api/v1/films?sort=imdb_rating,date или так /api/v1/films?sort=imdb_rating&sort=date
> 
> ок, делаем списком, как и genre?

да

2024-01-22 15:46 UTC, AndreyNikitsich commented on src/services/film.py
> +            genre: str | None
так

2024-01-22 15:49 UTC, AndreyNikitsich commented on src/core/config.py
> +    CACHE_EXPIRE_IN_SECONDS: int = Field(default=(60 * 5))
можно попробовать плагин активировать https://docs.pydantic.dev/latest/integrations/mypy/#enabling-the-plugin

2024-01-23 09:12 UTC, AndreyNikitsich commented on src/services/film.py
> +        с необязательным фильтром по жанрам.
сортировка ведь тоже не обязательна в поиске, можем это отразить в коде ?

2024-01-23 09:20 UTC, AndreyNikitsich requested changes

2024-01-23 09:20 UTC, AndreyNikitsich commented on src/models/film.py
> +    director: List[Optional[str]]
мы из эластика получаем список строк, среди строк не должно быть типа None

2024-01-23 09:20 UTC, AndreyNikitsich commented on src/models/film.py
> +    actors: List[Optional[FilmPerson]]
аналогично комменту выше - мы получаем список обьектов персон, среди них нет None. Структура индекса из прошлого спринта https://code.s3.yandex.net/middle-python/learning-materials/es_schema.txt

2024-01-23 09:20 UTC, AndreyNikitsich commented on src/services/film.py
> +            genre: Optional[List[str]]
если genre может быть None, давай сделаем ему присвоение None по умолчананию, чтобы это был опциональный параметр (аналогично и с sort)

2024-01-23 14:20 UTC, AndreyNikitsich approved these changes

2024-01-23 14:29 UTC, merged